"""PKM-style markdown export — one note per entity, alongside SQLite.

Why: data sovereignty. SQLite is the operational store (queries fast),
but markdown files are the *user-readable, user-portable* form. If Compass
disappears tomorrow, your contacts and company notes still live as plain
text you can open in Obsidian / VS Code / cat / git.

Layout (under SETTINGS.data_dir):
    data/contacts/<slug>.md      one per Connection
    data/companies/<slug>.md     one per company you have ≥1 connection at
    data/jobs/<slug>.md          one per Job (lightweight summary; full data still in DB)

Sync direction: **DB → markdown**. We do NOT parse markdown back into the DB
in this version (would require conflict resolution; out of scope).
The user can edit markdown for THEIR notes — those persist as long as we
don't overwrite their hand-written sections.

Hand-edit-safe strategy:
    Each .md has two parts:
      1. SYSTEM section (between BEGIN/END markers) — overwritten on each export
      2. USER section (everything else) — preserved on re-export

This means user notes in their own paragraph survive re-import, only the
auto-generated frontmatter + system block changes.

Toggle: COMPASS_PKM_EXPORT env var or settings.pkm_export_enabled. Off by
default to avoid surprising users who don't want files written.
"""
from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from sqlalchemy import select
from sqlalchemy.orm import Session

from ..models import Connection, Job, OutreachAttempt
from .connections import companies_with_connections, find_connections_at

log = logging.getLogger(__name__)

_BEGIN_MARKER = "<!-- COMPASS:SYSTEM:BEGIN -->"
_END_MARKER = "<!-- COMPASS:SYSTEM:END -->"

_SLUG_RE = re.compile(r"[^\w一-鿿\-]+", re.UNICODE)


def _slugify(s: str, max_len: int = 80) -> str:
    """ASCII-safe filename slug. Preserves CJK chars; replaces other punctuation."""
    s = (s or "").strip()
    s = _SLUG_RE.sub("-", s)
    s = re.sub(r"-+", "-", s).strip("-").lower()
    return s[:max_len] or "untitled"


def _settings_data_dir() -> Path:
    try:
        from flask import current_app
        return current_app.config["SETTINGS"].data_dir
    except Exception:
        return Path("data")


def _pkm_enabled() -> bool:
    """PKM export is opt-in. Returns True if env or settings flag is on."""
    import os
    if os.environ.get("COMPASS_PKM_EXPORT", "").lower() in ("1", "true", "yes", "on"):
        return True
    try:
        from flask import current_app
        return bool(getattr(current_app.config["SETTINGS"], "pkm_export_enabled", False))
    except Exception:
        return False


# ─────────────────────────────────────────────────────────
# Markdown sectioning — preserve user-written content
# ─────────────────────────────────────────────────────────


def _split_existing(path: Path) -> tuple[str, str]:
    """Split existing .md into (before_user_section, user_notes_section).

    Strategy: everything BEFORE the first SYSTEM:BEGIN marker is preserved as
    'pre' (rare — usually empty). The SYSTEM block itself is replaced. Anything
    AFTER SYSTEM:END is the user's notes — preserved as-is.

    If file doesn't exist: return ("", "").
    If no markers: treat ENTIRE existing content as user_notes (user's manual
    file that we're now supplementing).
    """
    if not path.exists():
        return ("", "")
    text = path.read_text(encoding="utf-8")
    if _BEGIN_MARKER not in text:
        return ("", text.strip() + "\n" if text.strip() else "")
    pre, _, rest = text.partition(_BEGIN_MARKER)
    if _END_MARKER in rest:
        _, _, user_notes = rest.partition(_END_MARKER)
        return (pre, user_notes.lstrip("\n"))
    # Malformed — has BEGIN but no END. Conservative: treat all post-BEGIN as user.
    return (pre, "\n" + rest.strip() + "\n")


def _wrap_system_block(body: str) -> str:
    """Wrap autogenerated body between BEGIN/END markers."""
    return f"{_BEGIN_MARKER}\n{body.rstrip()}\n{_END_MARKER}\n"


def _write_md(path: Path, system_body: str) -> None:
    """Write or update a .md file, preserving any user-edited section."""
    path.parent.mkdir(parents=True, exist_ok=True)
    pre, user_notes = _split_existing(path)
    parts: list[str] = []
    if pre.strip():
        parts.append(pre.rstrip() + "\n\n")
    parts.append(_wrap_system_block(system_body))
    if user_notes.strip():
        parts.append("\n" + user_notes.rstrip() + "\n")
    else:
        # Seed a placeholder for user notes
        parts.append("\n## Your notes\n\n_(your hand-written notes go here — "
                     "Compass will not overwrite this section)_\n")
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text("".join(parts), encoding="utf-8")
    tmp.replace(path)


# ─────────────────────────────────────────────────────────
# Per-entity rendering
# ─────────────────────────────────────────────────────────


def _render_connection_body(c: Connection) -> str:
    """Frontmatter + summary table for one Connection."""
    fm_lines = ["---"]
    fm_lines.append(f"name: \"{c.name}\"")
    if c.current_company:
        fm_lines.append(f"company: \"{c.current_company}\"")
    if c.current_title:
        fm_lines.append(f"title: \"{c.current_title}\"")
    if c.linkedin_url:
        fm_lines.append(f"linkedin: \"{c.linkedin_url}\"")
    if c.email:
        fm_lines.append(f"email: \"{c.email}\"")
    fm_lines.append(f"source: \"{c.source}\"")
    if c.connected_at:
        fm_lines.append(f"connected_at: {c.connected_at:%Y-%m-%d}")
    if c.last_contacted_at:
        fm_lines.append(f"last_contacted: {c.last_contacted_at:%Y-%m-%d}")
    fm_lines.append(f"compass_id: {c.id}")
    fm_lines.append(f"updated: {datetime.now(timezone.utc):%Y-%m-%d %H:%M}")
    fm_lines.append("---")

    body = ["", f"# {c.name}", ""]
    if c.current_title or c.current_company:
        body.append(f"**{c.current_title or '—'}**" + (f" @ {c.current_company}" if c.current_company else ""))
    if c.linkedin_url:
        body.append(f"\n[LinkedIn]({c.linkedin_url})")
    return "\n".join(fm_lines + body)


def _render_company_body(company_name: str, connections_at: list[Connection]) -> str:
    fm_lines = ["---"]
    fm_lines.append(f"company: \"{company_name}\"")
    fm_lines.append(f"connection_count: {len(connections_at)}")
    fm_lines.append(f"updated: {datetime.now(timezone.utc):%Y-%m-%d %H:%M}")
    fm_lines.append("---")

    body = ["", f"# {company_name}", ""]
    body.append(f"**{len(connections_at)} 个连接** 在此公司")
    body.append("")
    body.append("## 你认识的人")
    body.append("")
    for c in connections_at:
        title = c.current_title or "—"
        link = c.linkedin_url or ""
        line = f"- **{c.name}** · {title}"
        if link:
            line += f" · [LinkedIn]({link})"
        if c.connected_at:
            line += f" · 加为连接 {c.connected_at:%Y-%m}"
        body.append(line)
    return "\n".join(fm_lines + body)


def _render_job_body(job: Job, outreach_count: int) -> str:
    fm_lines = ["---"]
    fm_lines.append(f"title: \"{job.title}\"")
    if job.company:
        fm_lines.append(f"company: \"{job.company}\"")
    if job.location:
        fm_lines.append(f"location: \"{job.location}\"")
    fm_lines.append(f"status: {job.status}")
    if job.is_remote:
        fm_lines.append("remote: true")
    if job.salary_min:
        fm_lines.append(f"salary_min: {job.salary_min}")
        if job.salary_currency:
            fm_lines.append(f"salary_currency: {job.salary_currency}")
    if job.link:
        fm_lines.append(f"jd_link: \"{job.link}\"")
    fm_lines.append(f"compass_id: {job.id}")
    fm_lines.append(f"updated: {datetime.now(timezone.utc):%Y-%m-%d %H:%M}")
    fm_lines.append("---")

    body = ["", f"# {job.title}", ""]
    body.append(f"**{job.company or '—'}** · {job.location or '—'} · status: `{job.status}`")
    if outreach_count:
        body.append(f"\n📜 已对此 job 发出 **{outreach_count}** 次 outreach")
    if job.link:
        body.append(f"\n[原 JD]({job.link})")
    return "\n".join(fm_lines + body)


# ─────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────


def export_connection(c: Connection) -> Optional[Path]:
    """Write/update one Connection's .md. Returns the file path or None if disabled."""
    if not _pkm_enabled():
        return None
    if not c.active:
        return None
    base = _settings_data_dir() / "contacts"
    name_slug = _slugify(c.name) or "unnamed"
    short_id = c.id[:6] if c.id else ""
    fname = f"{name_slug}-{short_id}.md"
    path = base / fname
    _write_md(path, _render_connection_body(c))
    return path


def export_company(session: Session, company_name: str) -> Optional[Path]:
    if not _pkm_enabled():
        return None
    connections = find_connections_at(session, company_name, limit=200)
    if not connections:
        return None
    base = _settings_data_dir() / "companies"
    fname = f"{_slugify(company_name)}.md"
    path = base / fname
    _write_md(path, _render_company_body(company_name, connections))
    return path


def export_job(session: Session, job: Job) -> Optional[Path]:
    if not _pkm_enabled():
        return None
    base = _settings_data_dir() / "jobs"
    title_slug = _slugify(job.title or "untitled")
    fname = f"{title_slug}-{job.id[:6]}.md"
    outreach_count = session.execute(
        select(OutreachAttempt).where(OutreachAttempt.job_id == job.id)
    ).scalars().all().__len__()
    path = base / fname
    _write_md(path, _render_job_body(job, outreach_count))
    return path


def sync_all(session: Session) -> dict:
    """One-shot full sync. Useful after CSV import or migration. Returns counts."""
    if not _pkm_enabled():
        return {"enabled": False}
    counts = {"connections": 0, "companies": 0, "jobs": 0}

    for c in session.execute(select(Connection).where(Connection.active.is_(True))).scalars():
        if export_connection(c):
            counts["connections"] += 1

    for company, _cnt in companies_with_connections(session, limit=200):
        if export_company(session, company):
            counts["companies"] += 1

    for j in session.execute(
        select(Job).where(Job.deleted.is_(False))
    ).scalars().all()[:200]:  # cap at 200 to keep first sync fast
        if export_job(session, j):
            counts["jobs"] += 1

    return {"enabled": True, **counts}
