"""Resume theme registry — built-in + user-uploaded.

Themes are Jinja templates that receive a JSON Resume `r` object as context.
Built-ins live in package; user uploads live in `<data>/templates/`.

Variable convention (what users use in their templates):

    {{ r.basics.name }}              # str
    {{ r.basics.email }}             # str
    {{ r.basics.phone }}             # str
    {{ r.basics.location.address }}  # str
    {{ r.basics.summary }}           # str

    {% for w in r.work %}            # list
        {{ w.name }}                 # company
        {{ w.position }}
        {{ w.startDate }} – {{ w.endDate }}
        {% for h in w.highlights %}{{ h }}{% endfor %}
    {% endfor %}

    {% for e in r.education %} … {% endfor %}
    {% for s in r.skills %}    … {% endfor %}
    {% for p in r.projects %}  … {% endfor %}
    {% for l in r.languages %} … {% endfor %}

Built-in themes use Jinja's package loader so they pick up filters like
`local_dt` if needed. User themes use a sandboxed-string environment for
safety, but since Compass is local-only we don't need full sandboxing.
"""
from __future__ import annotations

import json
import logging
import re
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from flask import current_app
from jinja2 import Environment, FileSystemLoader, select_autoescape

log = logging.getLogger(__name__)


# ────────────────────────────────────────────────────────────
# Built-in themes (shipped as Jinja templates inside the package)
# ────────────────────────────────────────────────────────────

BUILTIN_THEMES: dict[str, dict] = {
    "classic": {
        "name": "经典 (Classic)",
        "description": "单栏极简风。学术 / 咨询常用。A4 一页友好。",
        "file": "export/themes/classic.html",
        "preview_color": "#2b5876",
    },
    "modern": {
        "name": "现代双栏 (Modern)",
        "description": "左 sidebar 显示联系方式 + skills，右栏 work / education。视觉对比强。",
        "file": "export/themes/modern.html",
        "preview_color": "#1f5f4d",
    },
    "compact": {
        "name": "紧凑技术 (Compact)",
        "description": "高密度，适合工程师 / 研究者多 bullet 内容。无衬线，紧凑行距。",
        "file": "export/themes/compact.html",
        "preview_color": "#3a3a3a",
    },
}


# ────────────────────────────────────────────────────────────
# User theme metadata (stored in <data>/templates.json)
# ────────────────────────────────────────────────────────────

@dataclass
class UserTheme:
    """A user-uploaded theme. ADR-0018 alignment layer: format-preserving DOCX
    rendering uses kind="docx" + docxtpl placeholders; HTML uses kind="html" +
    Jinja templates. The render_theme dispatcher picks engine by kind.
    """
    id: str
    name: str
    description: str
    file: str  # path RELATIVE to <data>/templates/ (e.g. "x.html" or "docx/x.docx")
    uploaded_at: str = ""
    kind: str = "html"  # "html" | "docx" — added 2026-05-07 (ADR-0018)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "file": self.file,
            "uploaded_at": self.uploaded_at,
            "kind": self.kind,
        }


def _user_themes_dir() -> Path:
    return Path(current_app.config["SETTINGS"].data_dir) / "templates"


def _user_themes_index() -> Path:
    return Path(current_app.config["SETTINGS"].data_dir) / "templates.json"


def _slugify_id(name: str) -> str:
    """Generate a safe id from a theme name."""
    s = re.sub(r"[^\w一-鿿-]+", "-", name.strip().lower(), flags=re.UNICODE)
    s = s.strip("-")
    return s or uuid.uuid4().hex[:8]


def load_user_themes() -> list[UserTheme]:
    """Load user theme index. Returns empty list if no index file.

    Forward-compat: filters unknown JSON keys so future field additions don't
    explode old loaders. Backward-compat: themes pre-2026-05-07 lack a `kind`
    field — UserTheme defaults that to "html".
    """
    p = _user_themes_index()
    if not p.exists():
        return []
    try:
        raw = json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        log.warning("user themes index unreadable: %s", e)
        return []
    out = []
    valid_keys = {"id", "name", "description", "file", "uploaded_at", "kind"}
    for t in raw.get("themes", []):
        clean = {k: v for k, v in t.items() if k in valid_keys}
        # Defense-in-depth: never let a hand-edited templates.json escape the
        # data/templates/ sandbox via `..` segments. Every legitimate theme.file
        # is generated by save_user_theme and lives under the directory.
        f = clean.get("file", "")
        if not isinstance(f, str) or not f or ".." in f or f.startswith(("/", "\\")):
            log.warning("user theme %r has suspicious file path %r — skipping",
                        clean.get("id"), f)
            continue
        out.append(UserTheme(**clean))
    return out


def save_user_themes(themes: list[UserTheme]) -> None:
    p = _user_themes_index()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        json.dumps(
            {"themes": [t.to_dict() for t in themes]},
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )


# ────────────────────────────────────────────────────────────
# Public API
# ────────────────────────────────────────────────────────────


def list_all_themes() -> list[dict]:
    """Return list of all available themes (built-in + user).

    For user themes, the `engine` field disambiguates HTML vs DOCX kind.
    `kind` stays "user" for UI grouping purposes (built-in vs user-uploaded).
    """
    out = []
    for tid, meta in BUILTIN_THEMES.items():
        out.append({
            "id": tid,
            "name": meta["name"],
            "description": meta["description"],
            "kind": "builtin",
            "engine": "html",
            "preview_color": meta.get("preview_color", "#666"),
        })
    for ut in load_user_themes():
        out.append({
            "id": f"user:{ut.id}",
            "name": ut.name,
            "description": ut.description,
            "kind": "user",
            "engine": ut.kind,  # html | docx
            "preview_color": "#8e7cc3" if ut.kind == "html" else "#7d6e6e",
            "uploaded_at": ut.uploaded_at,
        })
    return out


def render_theme(theme_id: str, resume: dict, *, job_id: Optional[str] = None):
    """Render the chosen theme.

    Returns:
        str  — for HTML themes (built-in or user kind="html")
        bytes — for DOCX user themes (kind="docx") — caller must serve as attachment

    Callers that don't care which engine is used should check `type()` of return value
    or use the format-specific helpers directly: render_html_theme / render_docx_theme.
    """
    if theme_id.startswith("user:"):
        uid = theme_id[len("user:"):]
        ut = _find_user_theme(uid)
        if ut is None:
            raise ValueError(f"User theme not found: {uid}")
        if ut.kind == "docx":
            return render_docx_theme(ut, resume, job_id=job_id)
        return _render_user_theme_html(ut, resume, job_id)
    return _render_builtin_theme(theme_id, resume, job_id)


def _find_user_theme(uid: str) -> Optional[UserTheme]:
    return next((t for t in load_user_themes() if t.id == uid), None)


def render_docx_theme(theme: UserTheme, resume: dict, *, job_id: Optional[str] = None) -> bytes:
    """ADR-0018 alignment layer: render the user's uploaded DOCX template with
    the JSON Resume payload as `r` context. Returns binary .docx bytes.

    Why this is an alignment layer: the LLM produced plain-text bullets +
    structured fields; this layer aligns that into the user's existing DOCX
    format (font / spacing / section headings / bullet styles all preserved
    via docxtpl's placeholder-substitution-on-XML approach).
    """
    if theme.kind != "docx":
        raise ValueError(f"Theme {theme.id} is kind={theme.kind!r}, not docx")
    file_path = _user_themes_dir() / theme.file
    if not file_path.exists():
        raise ValueError(f"DOCX template missing on disk: {file_path}")

    import io
    from docxtpl import DocxTemplate

    tpl = DocxTemplate(str(file_path))
    tpl.render({"r": resume, "job_id": job_id, "theme_id": f"user:{theme.id}"})
    out = io.BytesIO()
    tpl.save(out)
    return out.getvalue()


def _render_builtin_theme(theme_id: str, resume: dict, job_id: Optional[str]) -> str:
    if theme_id not in BUILTIN_THEMES:
        # Fallback to classic
        theme_id = "classic"
    template_path = BUILTIN_THEMES[theme_id]["file"]
    # Use Flask's render_template so we get filter access (local_dt etc.)
    from flask import render_template
    return render_template(template_path, r=resume, job_id=job_id, theme_id=theme_id)


def _render_user_theme_html(theme: UserTheme, resume: dict, job_id: Optional[str]) -> str:
    """Render an HTML user-uploaded theme via Jinja FileSystemLoader."""
    file_path = _user_themes_dir() / theme.file
    if not file_path.exists():
        raise ValueError(f"Theme file missing on disk: {file_path}")
    env = Environment(
        loader=FileSystemLoader(str(_user_themes_dir())),
        autoescape=select_autoescape(["html", "htm", "xml"]),
    )
    tpl = env.get_template(theme.file)
    return tpl.render(r=resume, job_id=job_id, theme_id=f"user:{theme.id}")


# ────────────────────────────────────────────────────────────
# Upload / save user theme
# ────────────────────────────────────────────────────────────


def save_user_theme(
    *,
    name: str,
    description: str,
    html: Optional[str] = None,
    data: Optional[bytes] = None,
    kind: str = "html",
) -> UserTheme:
    """Save a user-uploaded theme to disk + register in index.

    Args:
        html: HTML string (legacy signature, still supported). Forces kind="html".
        data: raw bytes (new signature). Use with kind="html" or "docx".
        kind: "html" or "docx".

    DOCX templates are stored under <data>/templates/docx/<id>.docx;
    HTML templates stay at <data>/templates/<id>.html for back-compat with
    pre-2026-05-07 file paths.
    """
    from datetime import datetime, timezone

    # Resolve content + kind
    if html is not None and data is None:
        if not html.strip():
            raise ValueError("Empty HTML.")
        data = html.encode("utf-8")
        kind = "html"  # html=... always means HTML, ignore caller's kind

    if data is None or not data:
        raise ValueError("must pass html= (str) or data= (bytes)")

    if kind == "html":
        try:
            decoded = data.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise ValueError(f"HTML must be utf-8: {exc}")
        if "<html" not in decoded.lower() and "<body" not in decoded.lower():
            log.info("Theme has no <html>/<body>; treating as fragment.")
    elif kind == "docx":
        # DOCX magic = PK (zip)
        if not data.startswith(b"PK"):
            raise ValueError("Not a valid .docx file (missing PK magic bytes)")
    else:
        raise ValueError(f"Unknown kind: {kind!r} (expected html or docx)")

    tid = _slugify_id(name)
    existing = {t.id for t in load_user_themes()}
    base = tid
    i = 2
    while tid in existing:
        tid = f"{base}-{i}"
        i += 1

    if kind == "html":
        fname = f"{tid}.html"  # top-level for back-compat
    else:
        fname = f"docx/{tid}.docx"  # subdir keeps it tidy

    out = _user_themes_dir() / fname
    try:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(data)
    except OSError as exc:
        # Surface as ValueError so route layer can show a friendly flash
        # instead of a 500. Caller treats ValueError as user-actionable.
        raise ValueError(f"无法保存模板文件: {exc}") from exc

    theme = UserTheme(
        id=tid,
        name=name.strip(),
        description=description.strip()[:240],
        file=fname,
        uploaded_at=datetime.now(timezone.utc).isoformat(),
        kind=kind,
    )
    themes = load_user_themes()
    themes.append(theme)
    save_user_themes(themes)
    log.info("Saved user theme id=%s file=%s kind=%s", tid, fname, kind)
    return theme


def delete_user_theme(uid: str) -> bool:
    """Delete a user theme. Returns True if deleted, False if not found."""
    themes = load_user_themes()
    match = next((t for t in themes if t.id == uid), None)
    if match is None:
        return False
    fpath = _user_themes_dir() / match.file
    if fpath.exists():
        try:
            fpath.unlink()
        except OSError as e:
            log.warning("Failed to delete file %s: %s", fpath, e)
    themes = [t for t in themes if t.id != uid]
    save_user_themes(themes)
    return True
