"""v4_add_factvariant_decomposition_translated

Revision ID: 45927a448510
Revises: f12de97ec81f
Create Date: 2026-05-06 12:52:28.856449
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '45927a448510'
down_revision: Union[str, None] = 'f12de97ec81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decomposition_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('translated_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_variants', schema=None) as batch_op:
        batch_op.drop_column('translated_json')
        batch_op.drop_column('decomposition_json')

    # ### end Alembic commands ###
