"""v4_add_job_matched_profile_id_adr0016

Revision ID: d199d52eda52
Revises: 45927a448510
Create Date: 2026-05-06 13:34:55.675824
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd199d52eda52'
down_revision: Union[str, None] = '45927a448510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_profile_id', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('matched_profile_id')

    # ### end Alembic commands ###
