"""baseline_pre_v4_structural_overhaul

Revision ID: f12de97ec81f
Revises: 
Create Date: 2026-05-06 12:37:14.601039
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f12de97ec81f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
